name: app
description: A new Flutter project.

version: 1.0.0+0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.1.0
  flutter_i18n: ^0.6.3
  font_awesome_flutter: ^8.4.0
  flutter_linkify: ^2.1.0
  flutter_form_builder: ^3.2.8
  location: ^2.3.5
  smooth_star_rating: ^1.0.3
  permission_handler: ^3.2.0
  intl: ^0.16.0
  rxdart: ^0.22.0
  random_string: ^1.1.0
  shared_preferences: ^0.5.6+1
  flutter_cache_manager: ^1.1.1
  store_redirect: ^1.0.1
  package_info: ^0.4.0+6
  flutter_facebook_login: ^3.0.0
  flutter_device_type: ^0.2.0
  instabug_flutter: ^8.7.0
  flutter_slidable: ^0.5.4
  webview_flutter: ^0.3.19+3
  flutter_staggered_grid_view: ^0.3.0
  flutter_plugin_pdf_viewer:
    git: git://github.com/VitalikShcherbyna/flutter_plugin_pdf_viewer.git
  awesome_dialog: ^0.0.4


  # Google Services
  cloud_firestore: ^0.12.10
  firebase_storage: ^3.0.6
  firebase_auth: ^0.14.0+5
  firebase_analytics: ^5.0.2
  google_maps_flutter: ^0.5.21
  geoflutterfire: ^2.0.3+2
  firebase_messaging: ^5.0.2
  google_sign_in: ^4.0.11

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher" 
  ios: true
  image_path_android: "assets/icon/icon_android.png"
  image_path_ios: "assets/icon/icon_ios.png"
  adaptive_icon_background: "assets/icon/icon_android.png"
  adaptive_icon_foreground: "assets/icon/icon_android.png"


flutter:
  uses-material-design: true
  assets:
    - assets/flutter_i18n/pl.json
    - assets/flutter_i18n/en.json
  
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-RegularItalic.ttf
          style: italic
    - family: Poppins Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-BoldItalic.ttf
          style: italic
    - family: Poppins Super Bold
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-BlackItalic.ttf
          style: italic
    - family: Poppins Thin
      fonts:
        - asset: fonts/Poppins-Thin.ttf
        - asset: fonts/Poppins-ThinItalic.ttf
          style: italic
    - family: Poppins Light
      fonts:
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-LightItalic.ttf
          style: italic
